# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - trichoip

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Java version
              uses: actions/setup-java@v1
              with:
                  java-version: "8"

            - name: Build with Maven
              run: mvn -Parure clean install

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: java-app
                  path: "${{ github.workspace }}/target/*.jar"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: java-app

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "etransportation-webapp-api"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A60EA667465847ABBDCC744BAC24D522 }}
                  package: "*.jar"

    push_to_backend:
        name: Push Backend
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: dockerracdockerrac
                  password: dockerracdockerrac

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: dockerracdockerrac/etransportation-backend-springboot:latest

            - name: Build and push Docker image ${{ steps.meta.outputs.tags }} | ${{ steps.meta.outputs.labels }}
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    push_to_database:
        name: Push Database
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: dockerracdockerrac
                  password: dockerracdockerrac

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: dockerracdockerrac/etransportation-db-mysql:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./Dockerfile.db.mysql
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
